### ISSUE TITLE
Add a simple webserver that reloads on recompile

### ISSUE THREAD

**Issue by kritzcreek** [kRITZCREEK/pscid#14]
Not entirely sure how to handle the bundling on this one, but I'll go with a naive webpack-incremental + browser-sync for now. HMR and webpack need changes to the actual application and that's too intrusive for my taste.

Changes:
1. A new `server` command. Usage:
   
   ```
   pscid server
   ```
2. A new `--entry` command line option 
   
   Specifies the module to start bundling from. Only makes sense in combination with server. Defaults to `Main`.
3. A new `--server-port` command line option
   
   Specifies the port to run the webserver on. Only makes sense in combination with server.

**Comment by rvion** [comment]
@kRITZCREEK is here a small note I wrote for myself:

# Live reload

Goal: See changes in the browser as soon as possible

### Solutions 1: pscid + webpack-dev-server

(💚  best solution so far)

Create a `./dist/index.html`

```html
<html>
 <body>
   <script src="bundle.js"></script>
   <script>Main.main()</script> <!-- <- NOTE THIS LINE -->
 </body>
</html>
```

Create a `./webpack.config.js`

```js
module.exports = {
    entry: {
        main: "./output/Main/index.js"
    },
    output: {
        path: __dirname,
        filename: "dist/bundle.js",
        library: "Main"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" }
        ]
    }
};
```

then
```
webpack-dev-server --progress --colors --content-base dist --watch
```

:white_check_mark: the bundle stays in memory, very fast
:red_circle:  no psc-bundle -> no DCE -> > 1Mb bundle for simple halogen projects


there is several options to trade between speed / size / debug infos

```
--compress
--display-error-details
--display-cached
...
```

### Solutions 2:  pulp + browser-sync

:warning: More than 10 times slower than solution 1 for minimal halogen projects : (

```shell
pulp build --watch --to dist/bunndle.js
browser-sync start --server dist --files "dist/*"
```
possible to speed it up (a little bit, not much) with some params:

```
pulp build --no-tco --no-magic-do --no-opts
```

### Solutions 3. pulp server

[documentation here](https://github.com/bodil/pulp#launching-a-development-server)

__pros__: easy to get started
__cons__: not much more than a toy

> It only provides the most basic functionality

> It's intended as a starting point only.

./html.index:
```html
<!doctype html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js"></script>
  </head>
  <body>
    <h1>Hello sailor!</h1>
    <script src="/app.js"></script>
  </body>
</html>
```

:memo: miss Main module invocation


### Solutions 4. use purs-loader

  I didn't try it because I don't really like the level of indirection.

  https://github.com/ethul/purs-loader
  https://github.com/ethul/purescript-webpack-example
  https://github.com/ethul/purescript-webpack-example/tree/fast-rebuilds

**Comment by kritzcreek** [comment]
Thanks for writing these down! It might be nice to document Option 1 somewhere if it's working so well for you! Maybe we could add it to the README.md or you could put it into a blogpost and I link to it from the README?

**Comment by kritzcreek** [comment]
I don't think this is a great idea anymore, I like the focused nature of the tool.

**Comment by Boscop** [comment]
So what's the currently recommended way to get auto building & reloading in the browser?

@rvion With your method, how are you invoking pulp? Just `pulp -w build`? And how do you actually make it reload the page in your browser?

**Comment by kritzcreek** [comment]
I'd suggest to use webpack's dev-server watching the output/ folder, and then you can use either `pscid` or any of the editor plugins to get fast rebuilds and reloads. 

See https://github.com/slamdata/purescript-halogen-template/blob/cebbb9fd48d438b5223c07630cc6104ec0e5d4cd/package.json#L6

EDIT:
I just want to make that explicit, in my opinion stay clear of things like purs-loader. Use only the JS bundling part of webpack!
